/**
 * Parity between the committed assistant corpus artifact and the reviewed data
 * it is generated from. These fail when a rule, source, or language pack is
 * added without regenerating (`bun run assistant:corpus`), when the artifact
 * drifts from the frontend ruleset version, or when anything unreviewed leaks
 * into what the assistant is allowed to cite.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { corpus as generatedCorpus } from '../../../services/rules-assistant/generated/rules-context-data.js';
import { guidanceEntries } from '$lib/guidance/entries.js';
import { reviewedLanguagePacks } from '$lib/languages/registry.js';
import { buildAssistantCorpusContent, corpusContentHash } from './assistant-corpus.js';
import type { AssistantCorpus } from './assistant-corpus-types.js';
import { currentRuleSet } from './data/rule-set.js';
import { sourceRegistry } from './data/sources.js';
import { standardizedSpellings } from './data/spelling.js';
import { harperRuleIds } from './harper.js';
import { ruleLookupTables } from './lookup-tables.js';
import { enabledRules } from './registry.js';

const root = join(__dirname, '../../..');
const rulesMd = readFileSync(join(root, 'docs/rules.md'), 'utf8');
const docDir = join(root, 'documentation');
const docFiles = readdirSync(docDir)
	.filter((f) => f.endsWith('.md'))
	.sort();
const documentationDocs = docFiles.map(
	(f) => `${f}\n${readFileSync(join(docDir, f), 'utf8').trim()}`
);
const committed: AssistantCorpus = generatedCorpus;

describe('assistant corpus parity', () => {
	it('keeps the committed JSON artifact equal to the typed data module', () => {
		// The JSON is still read at runtime by the Worker eval harness and as
		// fixture data, and it cannot carry a "do not edit" header — this is its
		// only guard against a hand-edit or a partial regeneration.
		const json: unknown = JSON.parse(
			readFileSync(join(root, 'services/rules-assistant/generated/rules-context.json'), 'utf8')
		);
		expect(json).toEqual(generatedCorpus);
	});
	it('keeps the Worker type artifact byte-equal to the producer contract', () => {
		const source = readFileSync(join(root, 'src/lib/rules/assistant-corpus-types.ts'), 'utf8');
		const generated = readFileSync(
			join(root, 'services/rules-assistant/generated/rules-context.ts'),
			'utf8'
		);
		expect(generated).toBe(
			'// Generated by bun run assistant:corpus from src/lib/rules/assistant-corpus-types.ts. Do not edit.\n\n' +
				source
		);
	});
	it('contains every enabled rule exactly once, with its slug, and nothing else', () => {
		const corpusIds = committed.rules.map((rule) => rule.id);
		expect(new Set(corpusIds).size).toBe(corpusIds.length);
		expect([...corpusIds].sort()).toEqual(enabledRules.map((rule) => rule.id).sort());
		const slugs = committed.rules.map((rule) => rule.slug);
		expect(new Set(slugs).size).toBe(slugs.length);
	});

	it('accounts for the full shipped ruleset: enabled rules plus Harper', () => {
		const all = [...committed.rules.map((rule) => rule.id), ...committed.harper.ruleIds].sort();
		expect(all).toEqual([...currentRuleSet.ruleIds].sort());
		expect(committed.harper.ruleIds).toEqual([...harperRuleIds]);
	});

	it('carries the table-shaped rules in full, not just their worked example', () => {
		expect(committed.lookups).toEqual(ruleLookupTables());
		const ruleIds = new Set(committed.rules.map((rule) => rule.id));
		for (const lookup of committed.lookups) {
			expect(ruleIds.has(lookup.ruleId), `${lookup.ruleId} has a table but no rule`).toBe(true);
		}
		// The regression this shipped for: `spelling.standardized` reached the
		// assistant as the single pair its policy example is, so asked what the
		// standardized spellings are it could only answer `Imma` → `I'ma`.
		const spellings = committed.lookups.find((lookup) => lookup.ruleId === 'spelling.standardized');
		expect(spellings?.entries).toHaveLength(standardizedSpellings.length);
		expect(spellings?.entries.length).toBeGreaterThan(20);
	});

	it('labels curated transcription mistakes so they cannot be cited as Genius policy', () => {
		const curated = committed.lookups
			.flatMap((lookup) => lookup.entries)
			.flatMap((entry) => entry.curatedMisspellings ?? []);
		expect(curated.length).toBeGreaterThan(0);
		const reviewedForms = new Set(
			committed.lookups
				.flatMap((lookup) => lookup.entries)
				.flatMap((entry) => [...entry.preferred, ...entry.instead])
		);
		for (const mistake of curated) {
			expect(reviewedForms.has(mistake), `${mistake} is offered as reviewed guidance`).toBe(false);
		}
	});

	it('cites only reviewed sources, and every source a rule cites is present', () => {
		const corpusSourceIds = new Set(committed.sources.map((source) => source.id));
		expect(corpusSourceIds.size).toBe(committed.sources.length);
		for (const source of committed.sources) {
			expect(sourceRegistry.get(source.id)?.reviewStatus).toBe('reviewed');
		}
		for (const rule of committed.rules) {
			expect(rule.sourceIds.length).toBeGreaterThan(0);
			for (const sourceId of rule.sourceIds) {
				expect(corpusSourceIds.has(sourceId), `${rule.id} cites missing source ${sourceId}`).toBe(
					true
				);
			}
		}
	});

	it('carries every guidance entry, citing only known sources and rules', () => {
		expect(committed.guidance.map((entry) => entry.id).sort()).toEqual(
			guidanceEntries.map((entry) => entry.id).sort()
		);
		const corpusSourceIds = new Set(committed.sources.map((source) => source.id));
		const ruleIds = new Set(committed.rules.map((rule) => rule.id));
		for (const entry of committed.guidance) {
			expect(entry.sourceIds.length, entry.id).toBeGreaterThan(0);
			for (const sourceId of entry.sourceIds) {
				expect(corpusSourceIds.has(sourceId), `${entry.id} cites missing ${sourceId}`).toBe(true);
			}
			for (const ruleId of entry.relatedRuleIds ?? []) {
				expect(ruleIds.has(ruleId), `${entry.id} points at missing ${ruleId}`).toBe(true);
			}
			// The entry's tier must be one its own cited sources establish, so the
			// assistant can never report a convention above its evidence. The
			// `lyriclint` advisories are the exception: their sources are context,
			// and the tier itself already says the claim is not Genius's.
			if (entry.authority !== 'lyriclint') {
				const tiers = entry.sourceIds.map(
					(sourceId) => committed.sources.find((source) => source.id === sourceId)?.authority
				);
				expect(tiers, entry.id).toContain(entry.authority);
			}
		}
	});

	it('represents all reviewed language packs and no unreviewed inventory entries', () => {
		expect(committed.languages.map((language) => language.tag).sort()).toEqual(
			reviewedLanguagePacks.map((pack) => pack.tag).sort()
		);
		expect(committed.languages).toHaveLength(8);
	});

	it('matches the frontend ruleset version', () => {
		expect(committed.ruleSetVersion).toBe(currentRuleSet.version);
	});

	it('is not stale: regenerating from the reviewed data reproduces the committed hash', async () => {
		const content = buildAssistantCorpusContent(rulesMd, documentationDocs);
		expect(await corpusContentHash(content)).toBe(committed.contentHash);
	});

	it('is deterministic', async () => {
		const first = buildAssistantCorpusContent(rulesMd, documentationDocs);
		const second = buildAssistantCorpusContent(rulesMd, documentationDocs);
		expect(await corpusContentHash(first)).toBe(await corpusContentHash(second));
		expect(second).toEqual(first);
	});

	it('excludes unreviewed sources and the unreviewed language inventory', () => {
		const unreviewed = [...sourceRegistry.values()].filter(
			(source) => source.reviewStatus !== 'reviewed'
		);
		const corpusSourceIds = new Set(committed.sources.map((source) => source.id));
		for (const source of unreviewed) {
			expect(corpusSourceIds.has(source.id)).toBe(false);
		}
		// The unreviewed 64-language inventory must not ride along; a reviewed
		// pack always carries header vocabulary.
		expect(committed.languages.every((language) => language.headerTerms.length > 0)).toBe(true);
	});
});
