/**
 * Regenerate the rules-assistant knowledge corpus:
 *
 *   bun run assistant:corpus
 *
 * Writes services/rules-assistant/generated/rules-context.json, its cast-free
 * typed data module, and its dependency-free TypeScript contract from the
 * frontend's own reviewed data.
 * The content hash excludes the timestamp, and
 * an unchanged hash preserves the existing build stamp, so a no-op generation
 * is byte-stable. The parity tests in src/lib/rules/assistant-corpus.test.ts
 * fail when the committed artifact is stale relative to the reviewed data.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { buildAssistantCorpus } from '../src/lib/rules/assistant-corpus.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'services/rules-assistant/generated/rules-context.json');
const typeSource = join(root, 'src/lib/rules/assistant-corpus-types.ts');
const typeTarget = join(root, 'services/rules-assistant/generated/rules-context.ts');
const dataTarget = join(root, 'services/rules-assistant/generated/rules-context-data.ts');
const GENERATED_TYPE_HEADER =
	'// Generated by bun run assistant:corpus from src/lib/rules/assistant-corpus-types.ts. Do not edit.\n\n';

/** The two stamp fields this script reads back off the committed artifact. */
interface ExistingCorpusStamp {
	generatedAt?: string;
	contentHash?: string;
}

const rulesMd = await readFile(join(root, 'docs/rules.md'), 'utf8');
const docDir = join(root, 'documentation');
// SAFETY: fallback value when directory read fails
const docFiles = await readdir(docDir).catch(() => [] as string[]);
const docMdFiles = docFiles.filter((f) => f.endsWith('.md')).sort();
const documentationDocs: string[] = [];
for (const file of docMdFiles) {
	const text = await readFile(join(docDir, file), 'utf8');
	documentationDocs.push(`${file}\n${text.trim()}`);
}

// SAFETY: this file is written by this script alone, a few lines below, from a
// corpus that always carries both fields — and both are read as optional here,
// so an artifact from an older generator is treated as having no stamp and
// regenerates rather than being trusted.
const existing = await readFile(target, 'utf8')
	.then((text) => JSON.parse(text) as ExistingCorpusStamp)
	.catch(() => undefined);
const candidate = await buildAssistantCorpus(rulesMd, new Date().toISOString(), documentationDocs);
// A no-op regeneration must be byte-stable. Preserve the build stamp whenever
// the reviewed content hash has not moved; a real corpus change receives a new
// stamp.
const corpus =
	existing?.contentHash === candidate.contentHash && existing.generatedAt
		? { ...candidate, generatedAt: existing.generatedAt }
		: candidate;

await mkdir(dirname(target), { recursive: true });
const prettierConfig = (await resolveConfig(target)) ?? {};
await writeFile(
	target,
	await format(JSON.stringify(corpus), { ...prettierConfig, parser: 'json' })
);
await writeFile(typeTarget, GENERATED_TYPE_HEADER + (await readFile(typeSource, 'utf8')));
// Resolved against the .ts path, not reused from the .json one, so a
// path- or extension-scoped Prettier override cannot desync the emit from
// what `prettier --check` expects of the committed file.
const dataPrettierConfig = (await resolveConfig(dataTarget)) ?? {};
await writeFile(
	dataTarget,
	await format(
		`// Generated by bun run assistant:corpus. Do not edit.\n` +
			`import type { AssistantCorpus } from './rules-context';\n\n` +
			`export const corpus = ${JSON.stringify(corpus)} satisfies AssistantCorpus;\n`,
		{ ...dataPrettierConfig, parser: 'typescript' }
	)
);
console.log(
	`Wrote ${target}\n` +
		`  ruleset ${corpus.ruleSetVersion} · ${corpus.rules.length} rules · ` +
		`${corpus.sources.length} sources · ${corpus.languages.length} languages · ` +
		`${corpus.lookups.reduce((sum, lookup) => sum + lookup.entries.length, 0)} lookup entries ` +
		`across ${corpus.lookups.length} tables\n` +
		`  content hash ${corpus.contentHash}`
);
